config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  
  resources :stories do #all the routes we have done in the past
    member do
      get 'upvote'
      get 'downvote'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/story.rb
class Story < ApplicationRecord
  has_many :votes
  
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  
  def score
    total = 0 
    votes.each do |vote|
      total = total + vote.value
    end
    return total
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vote.rb
class Vote < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @stories = Story.all
    @stories = @stories.sort do |x, y|
      y.score <=> x.score
  end
end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  def index
  end
  
  def new
    @story = Story.new
  end
  
  def create
    @story = Story.new
    @story.user_id = current_user.id
    @story.title = params[:story][:title]
    @story.url = params[:story][:url]
    @story.image = params[:story][:image]
    @story.save
    redirect_to '/'
  end
  
  def edit
    @story = Story.find(params[:id])
  end
  
  def update
    @story = Story.find(params[:id])
    @story.title = params[:story][:title]
    @story.url = params[:story][:url]
    @story.image = params[:story][:image]
    @story.save
    redirect_to '/'
  end
  
    def upvote
    vote = Vote.find_by(user_id: current_user.id, story_id: params[:id])
    if vote.nil?
      vote = Vote.new
      vote.user_id = current_user.id
      vote.story_id = params[:id]
      vote.value = 1
      vote.save
    else
      vote.value = 1
      vote.save
    end
    redirect_to '/'
  end
  
  def downvote
    vote = Vote.find_by(user_id: current_user.id, story_id: params[:id])
    if vote.nil?
      vote = Vote.new
      vote.user_id = current_user.id
      vote.story_id = params[:id]
      vote.value = -1
      vote.save
    else 
      vote.value = -1
      vote.save
    end
    redirect_to '/'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/home/index.html.erb
<% if user_signed_in? %>
  <%= link_to 'New Story', new_story_path %>
<% end %>

<% @stories.each do |story| %>
  <div class="media">
    <div class="media-left">
      <%= image_tag story.image.url(:thumb), class: 'media-object' %>
    </div>
    <div class="media-body">
      <h4 class="media-heading">
        <%= story.score %>
        <%= link_to story.title, story.url %>
        </h4>
      <% if user_signed_in? && story.user_id == current_user.id %>
        <%= link_to 'Edit', edit_story_path(story) %>
      <% end %>
      <%= link_to  upvote_story_path(story) do %>
        <i class='fa fa-arrow-up'></i>
      <% end %>
      |
      <%= link_to downvote_story_path(story) do %>
        <i class='fa fa-arrow-down'></i>
      <% end %>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>News</title>
    <%= csrf_meta_tags %>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
     <nav class="navbar navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Breaking News</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="/">Home</a></li>
            <% if user_signed_in? %>
              <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to 'Login', new_user_session_path %></li>
            <% end %>
          </ul>
          <% if user_signed_in? %>
            <p class="navbar-text navbar-right"><%= current_user.email %></p>
          <% end %>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    <div class='container'>
      <%= yield %>
      </div>
  </body>
</html>

app/views/stories/_form.html.erb
<%= form_for @story, html: { multipart: true } do |f| %>
  <div class="form-group">
    <%= f.text_field :title, placeholder: 'Title', class: 'form-control' %> 
  </div>
  <div class="form-group">
    <%= f.text_field :url, placeholder: 'URL', class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.file_field :image, placeholder: 'Image', class: 'form-control' %>
  </div>
  <%= f.submit 'Save' %>
<% end %> 

app/views/stories/edit.html.erb
<h2>Edit Story</h2>

<%= render 'form' %>

app/views/stories/new.html.erb
<h2>New Story</h2>

<%= render 'form' %>